NUMPY

In [1]:
import numpy as np

## Numpy array

In [3]:
list = [1,2,3]
list

[1, 2, 3]

In [5]:
type(list)

list

In [7]:
array = np.array(list)

In [8]:
type(array)

numpy.ndarray

In [11]:
matrix_1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(matrix_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Hazır methodlar

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [17]:
matrix_2 = np.arange(5,50,5).reshape(3,3)
matrix_2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(2,89,7)

array([ 2. , 16.5, 31. , 45.5, 60. , 74.5, 89. ])

In [24]:
np.random.rand(5)

array([0.56817452, 0.67986571, 0.74980071, 0.30624577, 0.03155228])

In [25]:
np.random.rand(3,3)

array([[0.30493938, 0.03456262, 0.06540124],
       [0.83213918, 0.59958468, 0.84081615],
       [0.25489814, 0.43880756, 0.69215129]])

In [27]:
np.random.randn(4,4)

array([[ 1.7637195 ,  0.95785305,  0.15178219,  0.02818577],
       [ 1.83414913,  1.3329711 , -0.67311666,  0.07446152],
       [ 0.71848259, -0.92112497, -0.3443662 ,  1.69369413],
       [-0.89762294, -0.2114034 , -0.81764873,  0.76942228]])

In [28]:
np.random.randint(0,100)

72

In [29]:
np.random.randint(100,1000,5)

array([539, 813, 225, 917, 594])

In [31]:
np.random.seed(99)
np.random.rand(4)

array([0.67227856, 0.4880784 , 0.82549517, 0.03144639])

In [32]:
np.random.rand(4)

array([0.80804996, 0.56561742, 0.2976225 , 0.04669572])

In [33]:
np.random.seed(99)
np.random.rand(4)

array([0.67227856, 0.4880784 , 0.82549517, 0.03144639])

## MAX MIN

In [34]:
np.random.seed(99)
random = np.random.randint(0,100,15)
random

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1, 23, 35, 55, 65, 48])

In [35]:
random

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1, 23, 35, 55, 65, 48])

In [36]:
random.max()

82

In [37]:
random.min()

1

In [38]:
random.argmax()

5

In [39]:
random.argmin()

0

Shape & Type

In [44]:
array = np.arange(0,20).reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
array.shape

(5, 4)

In [47]:
array = array.reshape(1,20)

In [48]:
array.shape

(1, 20)

In [49]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [50]:
array = array.reshape(20,1)

In [51]:
array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [52]:
array.shape

(20, 1)

In [54]:
array = array.reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [55]:
array.reshape(10,2).shape

(10, 2)

In [56]:
array.dtype

dtype('int32')

In [59]:
array_float = np.linspace(14,88,22)

In [60]:
array_float

array([14.        , 17.52380952, 21.04761905, 24.57142857, 28.0952381 ,
       31.61904762, 35.14285714, 38.66666667, 42.19047619, 45.71428571,
       49.23809524, 52.76190476, 56.28571429, 59.80952381, 63.33333333,
       66.85714286, 70.38095238, 73.9047619 , 77.42857143, 80.95238095,
       84.47619048, 88.        ])

In [61]:
array_float.dtype

dtype('float64')

İşlem

In [67]:
arr_2d = np.arange(10,91,10).reshape(3,3)

In [68]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
np_arr_2d = np.array(([10,20,30],[40,50,60],[70,80,90]))

In [71]:
np_arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
islem_arr = arr_2d

In [73]:
islem_arr + 5

array([[15, 25, 35],
       [45, 55, 65],
       [75, 85, 95]])

In [74]:
islem_arr * 4

array([[ 40,  80, 120],
       [160, 200, 240],
       [280, 320, 360]])

In [75]:
islem_arr - 8

array([[ 2, 12, 22],
       [32, 42, 52],
       [62, 72, 82]])

In [76]:
islem_arr / 2

array([[ 5., 10., 15.],
       [20., 25., 30.],
       [35., 40., 45.]])

In [77]:
islem_arr ** 2

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]])

In [78]:
islem_arr + islem_arr

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180]])

In [79]:
islem_arr/islem_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
1 / islem_arr

array([[0.1       , 0.05      , 0.03333333],
       [0.025     , 0.02      , 0.01666667],
       [0.01428571, 0.0125    , 0.01111111]])

In [81]:
0 / islem_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
islem_arr / 0

C:\Users\emrek\AppData\Local\Temp\ipykernel_58220\1958604039.py:1: RuntimeWarning: divide by zero encountered in divide
  islem_arr / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [83]:
np.sqrt(islem_arr)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [84]:
np.cos(islem_arr)

array([[-0.83907153,  0.40808206,  0.15425145],
       [-0.66693806,  0.96496603, -0.95241298],
       [ 0.6333192 , -0.11038724, -0.44807362]])

In [85]:
np.tan(islem_arr)

array([[ 0.64836083,  2.23716094, -6.4053312 ],
       [-1.11721493, -0.27190061,  0.32004039],
       [ 1.22195992,  9.00365495, -1.99520041]])

In [86]:
np.tanh(islem_arr)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.log(islem_arr)

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

In [88]:
np.exp(islem_arr)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

## index işlemleri

In [90]:
idx_arr = np.arange(0,10)

In [91]:
idx_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
idx_arr[4]

4

In [93]:
idx_arr[2:5]

array([2, 3, 4])

In [94]:
idx_arr[2:5] = 99

In [95]:
idx_arr

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [97]:
idx_part = idx_arr[2:5]

In [98]:
idx_part

array([99, 99, 99])

In [99]:
idx_part[:] = 7

In [100]:
idx_part

array([7, 7, 7])

In [101]:
idx_arr

array([0, 1, 7, 7, 7, 5, 6, 7, 8, 9])

In [103]:
idx_copy = idx_arr.copy()
idx_copy

array([0, 1, 7, 7, 7, 5, 6, 7, 8, 9])

In [104]:
idx_arr < 6

array([ True,  True, False, False, False,  True, False, False, False,
       False])

## istatistik ifadeler

In [107]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
arr.sum()

45

In [109]:
idx_arr.sum()

57

In [110]:
idx_arr.mean()

5.7

In [111]:
arr.mean()

4.5

In [112]:
arr.std()

2.8722813232690143

In [113]:
arr.var()

8.25